version: "3.9"

services:
  mysql:
    image: mysql
    container_name: mysql
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gestionapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db-data:/var/lib/mysql